/* Filename: [ name of this file…].js
   Target html: [ what is the html file(s) linked to this js…] 
   Purpose : [ a html file may have multiple js files. What does this one do?…]
   Author: [ your name…]
   Date written: [ …]
   Revisions:  [ your name, what, when…]
*/

// [ brief comment on what the function does…]
function init() {
}

document.write("This line of text is generated by text stored in script08.js");
document.write("This is another line of text that is generated by text stored in script08.js");



window.onload = init;  
